version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  ApplicationStop:
    - location: stop_service.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start_service.sh
      timeout: 300
      runas: root
    